server:
  port: 8080

jwt:
  secret-key: 2di67@3*&89cew62npor3ew#0-^ghert32!245YN$3tr78ONper
  expiration-time: 900000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb
    username: vinny
    password: 2727
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect